### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by zoepage** [hoodiehq-archive/documentation#87]
Here are the next steps to take:
- [x] adding new design 
- [x] moving all design files to src folder
- [x] review content structure 
- [x] add all content to the aside menu
- [x] new structure for content (smart URLS) 
- [x] add subnavigation
- [x] add templates for subnavigation 
- [x] add cheatsheet to footer
- [x] change folder structure (translations)
- [x] translate navigation and initial pages in german (translations)
- [x] add lang switch to the docs (translations)
- [x] add code highlighting
- [x] add doc's link to website and blog
- [x] review content 
- [ ] add hoodie-css-framework to the repo and delete internal styles
  (after extracting it from the website and blog)

**Comment by espy** [comment]
Code highlighting is in, at least on a global level, but it requires setting the language on each code block like this:

In HTML:

```
<pre><code class="language-javascript">
console.log('otters');
</code></pre>
```

In Markdown

``````
```javascript
console.log('yo');
``` // Ignore this comment, it's for github's formatter
``````

Note that the language identifier for HTML is not `HTML`, but `markup`.

Since we're editing all the docs and examples anyway, this will eventually get closed.

**Comment by zoepage** [comment]
Could you please add this to the README.md and also ping the translation teams, so they can fix that in their translations? thank you <3
